### ISSUE TITLE
What i am doing wrong ?

### ISSUE THREAD

**Issue by Menta2L** [shwoodard/jsonapi#36]
Probably its not a bug just don’t know how to use it 

Can you guys point me in some direction

Here is my case
```go
type Domain struct {
	ID        int       `gorm:"primary_key" sql:"AUTO_INCREMENT" json:"id" jsonapi:"primary,domains"`
	CreatedAt time.Time \`sql:"DEFAULT:current_timestamp" json:"created_at" jsonapi:"attr,created_at"\`
	UpdatedAt time.Time `json:"updated_at" jsonapi:"attr,updated_at"`
	Name                string        `gorm:"type:varchar(255);unique_index;not null" json:"name" jsonapi:"attr,name"`
	Active              bool          `gorm:"not null" sql:"DEFAULT:true" json:"active" jsonapi:"attr,active"`
	Description         string        `gorm:"type:varchar(255)" json:"description" jsonapi:"attr,description"`
	SenderBccAddress    string        `gorm:"type:varchar(255)" json:"sender_bcc_address" jsonapi:"attr,sender_bcc_address"`
	RecipientBccAddress string        `gorm:"type:varchar(255)" json:"recipient_bcc_address" jsonapi:"attr,recipient_bcc_address"`
	Backupmx            bool          `gorm:"not null" sql:"DEFAULT:false" json:"backupmx jsonapi:"attr,backupmx"`
	Transport           string        `gorm:"type:varchar(50);not null" sql:"DEFAULT:'dovecot'" json:"transport" jsonapi:"attr,transport"`
}
```

Fetching data : 
```go
func listDomains(w http.ResponseWriter, r *http.Request) {
	jsonapiRuntime := jsonapi.NewRuntime().Instrument("domains.list")
    var domains []models.Domain
    Rdbms.Find(&domains)
    domainInterface := make([]interface{}, len(domains))
    for i, domain := range domains {
    domainInterface[i] = domain
    }
    Log.Infof(" >>>>>>>>>>>> %q",domainInterface)
	w.WriteHeader(200)
	w.Header().Set("Content-Type", "application/vnd.api+json")
	if err := jsonapiRuntime..MarshalManyPayload(w, domainInterface); err != nil {
		http.Error(w, err.Error(), 500)
	}
}
```

The error : 
```go
`2016-07-15T16:02:17.502 listDomains ▶ INFO   >>>>>>>>>>>> [{'\x01' "2016-07-14 22:40:39 +0000 UTC" "2016-07-14 22:40:39 +0000 UTC" "servr-lab.info" %!q(bool=true) "" "" "" %!q(bool=false) "dovecot"}]
2016/07/15 16:02:17 http: panic serving 89.25.32.29:36542: reflect: call of reflect.Value.Elem on struct Value
goroutine 14 [running]:
net/http.(*conn).serve.func1(0xc82016d580)
        /root/.gvm/gos/go1.6/src/net/http/server.go:1389 +0xc1
panic(0x8d42a0, 0xc8201a1380)
        /root/.gvm/gos/go1.6/src/runtime/panic.go:426 +0x4e9
reflect.Value.Elem(0x956240, 0xc82014d180, 0x99, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.6/src/reflect/value.go:735 +0x228
github.com/shwoodard/jsonapi.visitModelNode(0x956240, 0xc82014d180, 0xc82046d480, 0x1, 0xc8204443f0, 0x0, 0x0)
        /srv/projects/vmail/src/github.com/shwoodard/jsonapi/response.go:173 +0x106
github.com/shwoodard/jsonapi.MarshalMany(0xc820168350, 0x1, 0x1, 0x30, 0x0, 0x0)
        /srv/projects/vmail/src/github.com/shwoodard/jsonapi/response.go:122 +0xe9
github.com/shwoodard/jsonapi.MarshalManyPayload(0x7fd17bd3e5e0, 0xc82018c4e0, 0xc820168350, 0x1, 0x1, 0x0, 0x0)
        /srv/projects/vmail/src/github.com/shwoodard/jsonapi/response.go:100 +0x57
github.com/shwoodard/jsonapi.(*Runtime).MarshalManyPayload.func1(0x0, 0x0)
        /srv/projects/vmail/src/github.com/shwoodard/jsonapi/runtime.go:71 +0x64
github.com/shwoodard/jsonapi.(*Runtime).instrumentCall(0xc8201ac368, 0x2, 0x3, 0xc82046d698, 0x0, 0x0)
        /srv/projects/vmail/src/github.com/shwoodard/jsonapi/runtime.go:83 +0x59
github.com/shwoodard/jsonapi.(*Runtime).MarshalManyPayload(0xc8201ac368, 0x7fd17bd3e5e0, 0xc82018c4e0, 0xc820168350, 0x1, 0x1, 0x0, 0x0)
        /srv/projects/vmail/src/github.com/shwoodard/jsonapi/runtime.go:72 +0x93
vmail/core.listDomains(0x7fd17bd3e2b0, 0xc82018c4e0, 0xc8201b8540)`
```

**Comment by aren55555** [comment]
@Menta2L your `Domain` struct should be:

```go
type Domain struct {
	ID                  int       `gorm:"primary_key" sql:"AUTO_INCREMENT" json:"id" jsonapi:"primary,domains"`
	CreatedAt           time.Time `sql:"DEFAULT:current_timestamp" json:"created_at" jsonapi:"attr,created_at"`
	UpdatedAt           time.Time `json:"updated_at" jsonapi:"attr,updated_at"`
	Name                string    `gorm:"type:varchar(255);unique_index;not null" json:"name" jsonapi:"attr,name"`
	Active              bool      `gorm:"not null" sql:"DEFAULT:true" json:"active" jsonapi:"attr,active"`
	Description         string    `gorm:"type:varchar(255)" json:"description" jsonapi:"attr,description"`
	SenderBccAddress    string    `gorm:"type:varchar(255)" json:"sender_bcc_address" jsonapi:"attr,sender_bcc_address"`
	RecipientBccAddress string    `gorm:"type:varchar(255)" json:"recipient_bcc_address" jsonapi:"attr,recipient_bcc_address"`
	Backupmx            bool      `gorm:"not null" sql:"DEFAULT:false" json:"backupmx" jsonapi:"attr,backupmx"`
	Transport           string    `gorm:"type:varchar(50);not null" sql:"DEFAULT:'dovecot'" json:"transport" jsonapi:"attr,transport"`
}
```
Note the removal of the `\` character in the `CreatedAt ` field and the addition of a closing `"` in the `json` annotation for the `Backupmx` field.
